### ISSUE TITLE
CONTRIBUTING - feedbacks / problems

### ISSUE THREAD

**Issue by martinp7** [DeepChainBio/bio-transformers#32]
While doing the MR #31 I followed the CONTRIBUTING step-by-step and I have some feedbacks / remarks / problems:

1. Once the conda environment is installed, the `pre-commit` was not available (even if the it is available in `environment_dev.yaml`). I tried to run `pip install pre-commit` but it did not solve the issue. However, using `conda install -c conda-forge pre-commit` solved the issue. Maybe we can update the `environment_dev.yaml` by moving the `pre-commit` requirement from `pip` to `dependencies` (+ add `conda-forge` channel which is commented for now)
2. Once the `pre-commit` is installed, it is advised to launch `pre-commit run --all-files`. With the latest version of `main` I had several errors, cf:
![image](https://user-images.githubusercontent.com/27958621/133237104-1b353510-79ee-44eb-b8e8-bd9ab7eb2c94.png)
3. Regarding the `pre-commit`, `isort` is mentioned in the `CONTRIBUTING.md` but it is not defined in the `.pre-commit-config.yaml` (Remark: `mypy` is used but not mentioned in the `CONTRIBUTING.md`)
4. To ensure the git conventions you can add a hook in the pre-commit by adding the following lines in the .pre-commit-config.yaml`:
```yml
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
```
